// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feelocker/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryLockedFeeRequest struct {
	LockedFeeId uint64 `protobuf:"varint,1,opt,name=locked_fee_id,json=lockedFeeId,proto3" json:"locked_fee_id,omitempty"`
}

func (m *QueryLockedFeeRequest) Reset()         { *m = QueryLockedFeeRequest{} }
func (m *QueryLockedFeeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLockedFeeRequest) ProtoMessage()    {}
func (*QueryLockedFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4dc338670fa6fbd, []int{0}
}
func (m *QueryLockedFeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockedFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockedFeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockedFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockedFeeRequest.Merge(m, src)
}
func (m *QueryLockedFeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockedFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockedFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockedFeeRequest proto.InternalMessageInfo

func (m *QueryLockedFeeRequest) GetLockedFeeId() uint64 {
	if m != nil {
		return m.LockedFeeId
	}
	return 0
}

type QueryLockedFeeResponse struct {
	LockedFee *LockedFee `protobuf:"bytes,1,opt,name=locked_fee,json=lockedFee,proto3" json:"locked_fee,omitempty"`
}

func (m *QueryLockedFeeResponse) Reset()         { *m = QueryLockedFeeResponse{} }
func (m *QueryLockedFeeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLockedFeeResponse) ProtoMessage()    {}
func (*QueryLockedFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4dc338670fa6fbd, []int{1}
}
func (m *QueryLockedFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockedFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockedFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockedFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockedFeeResponse.Merge(m, src)
}
func (m *QueryLockedFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockedFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockedFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockedFeeResponse proto.InternalMessageInfo

func (m *QueryLockedFeeResponse) GetLockedFee() *LockedFee {
	if m != nil {
		return m.LockedFee
	}
	return nil
}

type QueryLockedFeeListRequest struct {
	AccountAddress string `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Status         STATUS `protobuf:"varint,2,opt,name=status,proto3,enum=guardian.v1.STATUS" json:"status,omitempty"`
}

func (m *QueryLockedFeeListRequest) Reset()         { *m = QueryLockedFeeListRequest{} }
func (m *QueryLockedFeeListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLockedFeeListRequest) ProtoMessage()    {}
func (*QueryLockedFeeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4dc338670fa6fbd, []int{2}
}
func (m *QueryLockedFeeListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockedFeeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockedFeeListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockedFeeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockedFeeListRequest.Merge(m, src)
}
func (m *QueryLockedFeeListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockedFeeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockedFeeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockedFeeListRequest proto.InternalMessageInfo

func (m *QueryLockedFeeListRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *QueryLockedFeeListRequest) GetStatus() STATUS {
	if m != nil {
		return m.Status
	}
	return STATUS_CLAIMABLE
}

type QueryLockedFeeListResponse struct {
	LockedFees []*LockedFee `protobuf:"bytes,1,rep,name=locked_fees,json=lockedFees,proto3" json:"locked_fees,omitempty"`
}

func (m *QueryLockedFeeListResponse) Reset()         { *m = QueryLockedFeeListResponse{} }
func (m *QueryLockedFeeListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLockedFeeListResponse) ProtoMessage()    {}
func (*QueryLockedFeeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4dc338670fa6fbd, []int{3}
}
func (m *QueryLockedFeeListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockedFeeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockedFeeListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockedFeeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockedFeeListResponse.Merge(m, src)
}
func (m *QueryLockedFeeListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockedFeeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockedFeeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockedFeeListResponse proto.InternalMessageInfo

func (m *QueryLockedFeeListResponse) GetLockedFees() []*LockedFee {
	if m != nil {
		return m.LockedFees
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryLockedFeeRequest)(nil), "guardian.v1.QueryLockedFeeRequest")
	proto.RegisterType((*QueryLockedFeeResponse)(nil), "guardian.v1.QueryLockedFeeResponse")
	proto.RegisterType((*QueryLockedFeeListRequest)(nil), "guardian.v1.QueryLockedFeeListRequest")
	proto.RegisterType((*QueryLockedFeeListResponse)(nil), "guardian.v1.QueryLockedFeeListResponse")
}

func init() { proto.RegisterFile("feelocker/v1/query.proto", fileDescriptor_c4dc338670fa6fbd) }

var fileDescriptor_c4dc338670fa6fbd = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0xeb, 0x12, 0x41,
	0x1c, 0xc6, 0x1d, 0xab, 0x1f, 0x38, 0x4b, 0x06, 0x13, 0x89, 0x2d, 0xb2, 0xc8, 0x06, 0x69, 0x08,
	0x3b, 0x68, 0xff, 0x0e, 0x75, 0xb1, 0x43, 0x20, 0x08, 0xd1, 0xaa, 0x97, 0x2e, 0x32, 0xee, 0x8c,
	0xeb, 0xd2, 0x36, 0xb3, 0xee, 0xcc, 0x4a, 0x22, 0x5e, 0x3a, 0x77, 0x08, 0x7a, 0x09, 0xbd, 0x8d,
	0x5e, 0x40, 0x47, 0xa1, 0x4b, 0xc7, 0xd0, 0x5e, 0x48, 0xb8, 0xbb, 0xfe, 0x59, 0xab, 0xed, 0xb8,
	0xdf, 0x7d, 0xbe, 0xcf, 0xf3, 0x79, 0x66, 0x06, 0x56, 0xa7, 0x8c, 0xf9, 0xc2, 0x79, 0xcb, 0x42,
	0xbc, 0x68, 0xe3, 0x79, 0xc4, 0xc2, 0xa5, 0x15, 0x84, 0x42, 0x09, 0xa4, 0xb9, 0x11, 0x09, 0xa9,
	0x47, 0xb8, 0xb5, 0x68, 0xeb, 0x35, 0x57, 0x08, 0xd7, 0x67, 0x98, 0x04, 0x1e, 0x26, 0x9c, 0x0b,
	0x45, 0x94, 0x27, 0xb8, 0x4c, 0xa4, 0x7a, 0x2d, 0x63, 0x72, 0xfc, 0x48, 0xfe, 0x9a, 0xcf, 0xe0,
	0x9d, 0xd7, 0x7b, 0xdf, 0xfe, 0x7e, 0x48, 0x5f, 0x32, 0x66, 0xb3, 0x79, 0xc4, 0xa4, 0x42, 0x26,
	0xbc, 0x19, 0x0b, 0xe9, 0x78, 0xca, 0xd8, 0xd8, 0xa3, 0x55, 0x50, 0x07, 0xcd, 0xeb, 0xb6, 0xe6,
	0x1f, 0x84, 0x3d, 0x6a, 0xbe, 0x82, 0x95, 0xcb, 0x65, 0x19, 0x08, 0x2e, 0x19, 0x7a, 0x0c, 0xe1,
	0x69, 0x3b, 0x5e, 0xd5, 0x3a, 0x15, 0xeb, 0x0c, 0xda, 0x3a, 0xed, 0x94, 0x8e, 0x96, 0xe6, 0x1c,
	0xde, 0xcd, 0x1a, 0xf6, 0x3d, 0xa9, 0x0e, 0x44, 0x0d, 0x78, 0x8b, 0x38, 0x8e, 0x88, 0xb8, 0x1a,
	0x13, 0x4a, 0x43, 0x26, 0x65, 0x6c, 0x5c, 0xb2, 0xcb, 0xe9, 0xb8, 0x9b, 0x4c, 0x51, 0x0b, 0x5e,
	0x49, 0x45, 0x54, 0x24, 0xab, 0xc5, 0x3a, 0x68, 0x96, 0x3b, 0xb7, 0x33, 0xc1, 0x83, 0x61, 0x77,
	0x38, 0x1a, 0xd8, 0xa9, 0xc4, 0x1c, 0x41, 0xfd, 0x6f, 0x91, 0x69, 0x8f, 0xa7, 0x50, 0x3b, 0xf5,
	0xd8, 0xe7, 0x5d, 0xcb, 0x29, 0x02, 0x8f, 0x45, 0x64, 0xe7, 0x6b, 0x11, 0xde, 0x88, 0x7d, 0xd1,
	0x17, 0x00, 0xd1, 0x9f, 0x09, 0xe8, 0x7e, 0xc6, 0xe4, 0x9f, 0xad, 0xf5, 0xc6, 0x7f, 0x75, 0x09,
	0xaa, 0xf9, 0xfc, 0xc3, 0xf7, 0x5f, 0x9f, 0x8b, 0x4f, 0xd0, 0x23, 0x9c, 0xb9, 0xf0, 0x33, 0x7c,
	0xbc, 0xba, 0x38, 0xbf, 0x35, 0x5e, 0x25, 0xa7, 0xb0, 0x46, 0x1f, 0x01, 0x2c, 0x67, 0xcd, 0x91,
	0x99, 0x93, 0x7c, 0xa0, 0xbb, 0x97, 0xab, 0x49, 0xc9, 0xda, 0x31, 0x59, 0x0b, 0x3d, 0xc8, 0x21,
	0xcb, 0xbc, 0xb5, 0xf5, 0x8b, 0xde, 0xb7, 0xad, 0x01, 0x36, 0x5b, 0x03, 0xfc, 0xdc, 0x1a, 0xe0,
	0xd3, 0xce, 0x28, 0x6c, 0x76, 0x46, 0xe1, 0xc7, 0xce, 0x28, 0xbc, 0xc1, 0xae, 0xa7, 0x66, 0xd1,
	0xc4, 0x72, 0xc4, 0x3b, 0x3c, 0x21, 0x9c, 0xc6, 0xcf, 0xd8, 0x11, 0x3e, 0x76, 0x66, 0xc4, 0xe3,
	0xf8, 0xfd, 0x59, 0x86, 0x5a, 0x06, 0x4c, 0x4e, 0xae, 0x62, 0xc5, 0xc3, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x77, 0x72, 0x00, 0x23, 0x4d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryLockedFeeList(ctx context.Context, in *QueryLockedFeeListRequest, opts ...grpc.CallOption) (*QueryLockedFeeListResponse, error)
	QueryLockedFee(ctx context.Context, in *QueryLockedFeeRequest, opts ...grpc.CallOption) (*QueryLockedFeeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryLockedFeeList(ctx context.Context, in *QueryLockedFeeListRequest, opts ...grpc.CallOption) (*QueryLockedFeeListResponse, error) {
	out := new(QueryLockedFeeListResponse)
	err := c.cc.Invoke(ctx, "/guardian.v1.Query/QueryLockedFeeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryLockedFee(ctx context.Context, in *QueryLockedFeeRequest, opts ...grpc.CallOption) (*QueryLockedFeeResponse, error) {
	out := new(QueryLockedFeeResponse)
	err := c.cc.Invoke(ctx, "/guardian.v1.Query/QueryLockedFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryLockedFeeList(context.Context, *QueryLockedFeeListRequest) (*QueryLockedFeeListResponse, error)
	QueryLockedFee(context.Context, *QueryLockedFeeRequest) (*QueryLockedFeeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryLockedFeeList(ctx context.Context, req *QueryLockedFeeListRequest) (*QueryLockedFeeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLockedFeeList not implemented")
}
func (*UnimplementedQueryServer) QueryLockedFee(ctx context.Context, req *QueryLockedFeeRequest) (*QueryLockedFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLockedFee not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryLockedFeeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLockedFeeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryLockedFeeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guardian.v1.Query/QueryLockedFeeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryLockedFeeList(ctx, req.(*QueryLockedFeeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryLockedFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLockedFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryLockedFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guardian.v1.Query/QueryLockedFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryLockedFee(ctx, req.(*QueryLockedFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guardian.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryLockedFeeList",
			Handler:    _Query_QueryLockedFeeList_Handler,
		},
		{
			MethodName: "QueryLockedFee",
			Handler:    _Query_QueryLockedFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feelocker/v1/query.proto",
}

func (m *QueryLockedFeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockedFeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockedFeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LockedFeeId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LockedFeeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockedFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockedFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockedFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LockedFee != nil {
		{
			size, err := m.LockedFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockedFeeListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockedFeeListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockedFeeListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockedFeeListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockedFeeListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockedFeeListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LockedFees) > 0 {
		for iNdEx := len(m.LockedFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LockedFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryLockedFeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LockedFeeId != 0 {
		n += 1 + sovQuery(uint64(m.LockedFeeId))
	}
	return n
}

func (m *QueryLockedFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LockedFee != nil {
		l = m.LockedFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLockedFeeListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	return n
}

func (m *QueryLockedFeeListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LockedFees) > 0 {
		for _, e := range m.LockedFees {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryLockedFeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockedFeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockedFeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedFeeId", wireType)
			}
			m.LockedFeeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockedFeeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockedFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockedFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockedFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LockedFee == nil {
				m.LockedFee = &LockedFee{}
			}
			if err := m.LockedFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockedFeeListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockedFeeListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockedFeeListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= STATUS(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockedFeeListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockedFeeListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockedFeeListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockedFees = append(m.LockedFees, &LockedFee{})
			if err := m.LockedFees[len(m.LockedFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
