// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guardian/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGuardedFeeRequest struct {
	GuardedFeeId uint64 `protobuf:"varint,1,opt,name=guarded_fee_id,json=guardedFeeId,proto3" json:"guarded_fee_id,omitempty"`
}

func (m *QueryGuardedFeeRequest) Reset()         { *m = QueryGuardedFeeRequest{} }
func (m *QueryGuardedFeeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGuardedFeeRequest) ProtoMessage()    {}
func (*QueryGuardedFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b83539d1eae17da, []int{0}
}
func (m *QueryGuardedFeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGuardedFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGuardedFeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGuardedFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGuardedFeeRequest.Merge(m, src)
}
func (m *QueryGuardedFeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGuardedFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGuardedFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGuardedFeeRequest proto.InternalMessageInfo

func (m *QueryGuardedFeeRequest) GetGuardedFeeId() uint64 {
	if m != nil {
		return m.GuardedFeeId
	}
	return 0
}

type QueryGuardedFeeResponse struct {
	GuardedFee *GuardedFee `protobuf:"bytes,1,opt,name=guarded_fee,json=guardedFee,proto3" json:"guarded_fee,omitempty"`
}

func (m *QueryGuardedFeeResponse) Reset()         { *m = QueryGuardedFeeResponse{} }
func (m *QueryGuardedFeeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGuardedFeeResponse) ProtoMessage()    {}
func (*QueryGuardedFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b83539d1eae17da, []int{1}
}
func (m *QueryGuardedFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGuardedFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGuardedFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGuardedFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGuardedFeeResponse.Merge(m, src)
}
func (m *QueryGuardedFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGuardedFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGuardedFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGuardedFeeResponse proto.InternalMessageInfo

func (m *QueryGuardedFeeResponse) GetGuardedFee() *GuardedFee {
	if m != nil {
		return m.GuardedFee
	}
	return nil
}

type QueryGuardedFeeListRequest struct {
	AccountAddress string `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Status         STATUS `protobuf:"varint,2,opt,name=status,proto3,enum=guardian.v1.STATUS" json:"status,omitempty"`
}

func (m *QueryGuardedFeeListRequest) Reset()         { *m = QueryGuardedFeeListRequest{} }
func (m *QueryGuardedFeeListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGuardedFeeListRequest) ProtoMessage()    {}
func (*QueryGuardedFeeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b83539d1eae17da, []int{2}
}
func (m *QueryGuardedFeeListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGuardedFeeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGuardedFeeListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGuardedFeeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGuardedFeeListRequest.Merge(m, src)
}
func (m *QueryGuardedFeeListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGuardedFeeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGuardedFeeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGuardedFeeListRequest proto.InternalMessageInfo

func (m *QueryGuardedFeeListRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *QueryGuardedFeeListRequest) GetStatus() STATUS {
	if m != nil {
		return m.Status
	}
	return STATUS_CLAIMABLE
}

type QueryGuardedFeeListResponse struct {
	GuardedFees []*GuardedFee `protobuf:"bytes,1,rep,name=guarded_fees,json=guardedFees,proto3" json:"guarded_fees,omitempty"`
}

func (m *QueryGuardedFeeListResponse) Reset()         { *m = QueryGuardedFeeListResponse{} }
func (m *QueryGuardedFeeListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGuardedFeeListResponse) ProtoMessage()    {}
func (*QueryGuardedFeeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b83539d1eae17da, []int{3}
}
func (m *QueryGuardedFeeListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGuardedFeeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGuardedFeeListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGuardedFeeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGuardedFeeListResponse.Merge(m, src)
}
func (m *QueryGuardedFeeListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGuardedFeeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGuardedFeeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGuardedFeeListResponse proto.InternalMessageInfo

func (m *QueryGuardedFeeListResponse) GetGuardedFees() []*GuardedFee {
	if m != nil {
		return m.GuardedFees
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGuardedFeeRequest)(nil), "guardian.v1.QueryGuardedFeeRequest")
	proto.RegisterType((*QueryGuardedFeeResponse)(nil), "guardian.v1.QueryGuardedFeeResponse")
	proto.RegisterType((*QueryGuardedFeeListRequest)(nil), "guardian.v1.QueryGuardedFeeListRequest")
	proto.RegisterType((*QueryGuardedFeeListResponse)(nil), "guardian.v1.QueryGuardedFeeListResponse")
}

func init() { proto.RegisterFile("guardian/v1/query.proto", fileDescriptor_7b83539d1eae17da) }

var fileDescriptor_7b83539d1eae17da = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2f, 0x4d, 0x2c,
	0x4a, 0xc9, 0x4c, 0xcc, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0x49, 0xe8, 0x95, 0x19, 0x4a, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7,
	0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6,
	0xe7, 0x15, 0x43, 0x94, 0x4a, 0x49, 0x21, 0x9b, 0x01, 0xd7, 0x06, 0x96, 0x53, 0xb2, 0xe3, 0x12,
	0x0b, 0x04, 0x99, 0xea, 0x0e, 0x12, 0x4e, 0x4d, 0x71, 0x4b, 0x4d, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x52, 0xe1, 0xe2, 0x4b, 0x87, 0x08, 0xc6, 0xa7, 0xa5, 0xa6, 0xc6, 0x67, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0xf1, 0xa4, 0xc3, 0x95, 0x7a, 0xa6, 0x28, 0x05, 0x73,
	0x89, 0x63, 0xe8, 0x2f, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xb2, 0xe0, 0xe2, 0x46, 0x32, 0x00,
	0xac, 0x9b, 0xdb, 0x48, 0x5c, 0x0f, 0xc9, 0xdd, 0x7a, 0x48, 0xba, 0xb8, 0x10, 0xc6, 0x2a, 0x15,
	0x71, 0x49, 0xa1, 0x19, 0xea, 0x93, 0x59, 0x5c, 0x02, 0x73, 0x98, 0x3a, 0x17, 0x7f, 0x62, 0x72,
	0x72, 0x7e, 0x69, 0x5e, 0x49, 0x7c, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0x31, 0xd8, 0x6c, 0xce,
	0x20, 0x3e, 0xa8, 0xb0, 0x23, 0x44, 0x54, 0x48, 0x9b, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4,
	0x58, 0x82, 0x49, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x18, 0xc5, 0xee, 0xe0, 0x10, 0xc7, 0x90, 0xd0,
	0xe0, 0x20, 0xa8, 0x12, 0xa5, 0x48, 0x2e, 0x69, 0xac, 0x76, 0x42, 0x3d, 0x63, 0xc5, 0xc5, 0x83,
	0xe4, 0x19, 0x90, 0x8d, 0xcc, 0xf8, 0x7c, 0xc3, 0x8d, 0xf0, 0x4d, 0xb1, 0xd1, 0x61, 0x26, 0x2e,
	0x56, 0xb0, 0xd9, 0x42, 0xcb, 0x18, 0xb9, 0x84, 0xb1, 0xd8, 0x22, 0xa4, 0x8e, 0x62, 0x0e, 0x6e,
	0xbf, 0x4b, 0x69, 0x10, 0x56, 0x08, 0x71, 0xb0, 0x92, 0x4d, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0xcc,
	0x84, 0x4c, 0xf4, 0x31, 0x62, 0x1f, 0xea, 0x07, 0xfd, 0x6a, 0xb4, 0x60, 0xac, 0xd5, 0xaf, 0x86,
	0x04, 0x46, 0xad, 0xd0, 0x04, 0x46, 0x2e, 0x7e, 0x34, 0xd3, 0x85, 0x94, 0xf1, 0xd9, 0x0d, 0x73,
	0xa0, 0x0a, 0x7e, 0x45, 0x50, 0xc7, 0x19, 0x81, 0x1d, 0xa7, 0x23, 0xa4, 0x85, 0xc7, 0x71, 0xa8,
	0x89, 0xaf, 0xd6, 0xc9, 0xe3, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92,
	0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0xf4,
	0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x93, 0x12, 0xf3, 0x52, 0xc0,
	0x29, 0x3b, 0x39, 0x3f, 0x47, 0x3f, 0x39, 0x23, 0x31, 0x33, 0x4f, 0xbf, 0x02, 0x61, 0x49, 0x49,
	0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b, 0x58, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x7a,
	0xc1, 0xed, 0x5c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryGuardedFeeList(ctx context.Context, in *QueryGuardedFeeListRequest, opts ...grpc.CallOption) (*QueryGuardedFeeListResponse, error)
	QueryGuardedFee(ctx context.Context, in *QueryGuardedFeeRequest, opts ...grpc.CallOption) (*QueryGuardedFeeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryGuardedFeeList(ctx context.Context, in *QueryGuardedFeeListRequest, opts ...grpc.CallOption) (*QueryGuardedFeeListResponse, error) {
	out := new(QueryGuardedFeeListResponse)
	err := c.cc.Invoke(ctx, "/guardian.v1.Query/QueryGuardedFeeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryGuardedFee(ctx context.Context, in *QueryGuardedFeeRequest, opts ...grpc.CallOption) (*QueryGuardedFeeResponse, error) {
	out := new(QueryGuardedFeeResponse)
	err := c.cc.Invoke(ctx, "/guardian.v1.Query/QueryGuardedFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryGuardedFeeList(context.Context, *QueryGuardedFeeListRequest) (*QueryGuardedFeeListResponse, error)
	QueryGuardedFee(context.Context, *QueryGuardedFeeRequest) (*QueryGuardedFeeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryGuardedFeeList(ctx context.Context, req *QueryGuardedFeeListRequest) (*QueryGuardedFeeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryGuardedFeeList not implemented")
}
func (*UnimplementedQueryServer) QueryGuardedFee(ctx context.Context, req *QueryGuardedFeeRequest) (*QueryGuardedFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryGuardedFee not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryGuardedFeeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGuardedFeeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryGuardedFeeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guardian.v1.Query/QueryGuardedFeeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryGuardedFeeList(ctx, req.(*QueryGuardedFeeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryGuardedFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGuardedFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryGuardedFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guardian.v1.Query/QueryGuardedFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryGuardedFee(ctx, req.(*QueryGuardedFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guardian.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryGuardedFeeList",
			Handler:    _Query_QueryGuardedFeeList_Handler,
		},
		{
			MethodName: "QueryGuardedFee",
			Handler:    _Query_QueryGuardedFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guardian/v1/query.proto",
}

func (m *QueryGuardedFeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGuardedFeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGuardedFeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GuardedFeeId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.GuardedFeeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGuardedFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGuardedFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGuardedFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GuardedFee != nil {
		{
			size, err := m.GuardedFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGuardedFeeListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGuardedFeeListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGuardedFeeListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGuardedFeeListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGuardedFeeListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGuardedFeeListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GuardedFees) > 0 {
		for iNdEx := len(m.GuardedFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GuardedFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGuardedFeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GuardedFeeId != 0 {
		n += 1 + sovQuery(uint64(m.GuardedFeeId))
	}
	return n
}

func (m *QueryGuardedFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GuardedFee != nil {
		l = m.GuardedFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGuardedFeeListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	return n
}

func (m *QueryGuardedFeeListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GuardedFees) > 0 {
		for _, e := range m.GuardedFees {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGuardedFeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGuardedFeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGuardedFeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardedFeeId", wireType)
			}
			m.GuardedFeeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GuardedFeeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGuardedFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGuardedFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGuardedFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardedFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GuardedFee == nil {
				m.GuardedFee = &GuardedFee{}
			}
			if err := m.GuardedFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGuardedFeeListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGuardedFeeListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGuardedFeeListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= STATUS(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGuardedFeeListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGuardedFeeListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGuardedFeeListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardedFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardedFees = append(m.GuardedFees, &GuardedFee{})
			if err := m.GuardedFees[len(m.GuardedFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
